## Azerbaijan BAKU

In [1]:
import pandas as pd
import requests
import time
from bs4 import BeautifulSoup
from datetime import date
from tqdm import tqdm

!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (1.1.0)

In [2]:
#go to https://www.whatismybrowser.com/
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
}
s = requests.Session()
# r = requests.get("https://www.bakuelectronics.az/catalog/", headers=headers)
# response = BeautifulSoup(r.text, features='html.parser')

In [3]:
with s.get("https://www.bakuelectronics.az/catalog/", headers=headers) as r:
    response = BeautifulSoup(r.text, features='html.parser')

In [4]:
# categories
categories_list = [
    item.find("a").get("href")
    for item in
    response.find(name="ul", attrs={"class":"nav-list js-main-menu-lvl-1"}).find_all("div", {"class": "main-menu__dropdown_second"})
]

In [5]:
categories_list

['https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/',
 'https://www.bakuelectronics.az/catalog/tv-audio-video/televizorlar/',
 'https://www.bakuelectronics.az/catalog/noutbuklar-komputerler/noutbuklar/',
 'https://www.bakuelectronics.az/catalog/iqlim-texnikasi/kombi/',
 'https://www.bakuelectronics.az/catalog/boyuk-meiset-texnikasi/soyuducular/',
 'https://www.bakuelectronics.az/catalog/kicik-meiset-texnikasi/metbex-komekcileri/',
 'https://www.bakuelectronics.az/catalog/gozellik-saglamliq/fen-daraqli-fenler/',
 'https://www.bakuelectronics.az/catalog/oyun-konsollari-oyunlar/oyun-konsollari/',
 'https://www.bakuelectronics.az/catalog/mebel/qonaq-otagi-ucun-mebel/',
 'https://www.bakuelectronics.az/catalog/qab-qacaq-tava-qazan/qab-qacaq/',
 'https://www.bakuelectronics.az/catalog/avto-ve-moto-mehsullari/avtomobil-yaglari-ve-mayeler/',
 'https://www.bakuelectronics.az/catalog/idman-ve-hobbi/velosipedler/',
 'https://www.bakuelectronics.az/catalog/ev-bag/isiqlandirilma/',
 'https://www.bakuelectronics.az/catalog/usaq-alemi/usaq-arabalari/']

In [6]:
categories = [
    cat.rsplit("/", 2)[-3]
    for cat in categories_list
]

In [7]:
# Define the Component of URL

base_url = "https://www.bakuelectronics.az/catalog/"
num_pages = 1

session = requests.Session()

In [8]:
# Create lists to store the data
product_categories = []
product_titles = []
product_prices = []

In [9]:
# Create a Scraping Loop

### Format of URL: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/?page=2 ###
for x in categories:
    for page in range(1, num_pages +1 , 1):
        # url = f"{base_url}{x}?page={page}"
        url = f"{x}?page={page}"

        # Send a GET request to the URL
        response = session.get(url, verify=False) #verify should be true and we have to put sertificate on this so theyknow that we are scraping
        print(f"Fetching page: {url}")

        # Check if the request was successful
        if response.status_code == 200:
            
            # Parse the HTML content using BeautifulSoup
            soup = BeautifulSoup(response.content, "html.parser")
            
            # Loop through the product listings and extract the data
            cols = soup.find_all('div', class_='flex__row--start js_pagination_container')
            
            # for row in rows:
            #     cols = row.find_all('div', class_='flex__row--start js_pagination_container')
                
            for col in cols:
                products = col.find_all('div', class_='product__card')
    
                for product in products:
                    category = x
                    title = product.find('a', class_ = 'product__title').get_text()
                    price = product.find('div', class_='product__price--cur').text.strip()
        
                    product_categories.append(category)
                    product_titles.append(title)
                    product_prices.append(price)
    
        time.sleep(3)
        print("sleep 3 seconds")

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/tv-audio-video?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/noutbuklar-komputerler?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/iqlim-texnikasi?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/boyuk-meiset-texnikasi?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/kicik-meiset-texnikasi?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/gozellik-saglamliq?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/oyun-konsollari-oyunlar?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/mebel?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/qab-qacaq-tava-qazan?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/avto-ve-moto-mehsullari?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/idman-ve-hobbi?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/ev-bag?page=1
sleep 3 seconds

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.bakuelectronics.az'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Fetching page: https://www.bakuelectronics.az/catalog/usaq-alemi?page=1
sleep 3 seconds

In [10]:
x = 'https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/'

for page in range(1, 27 , 1):
        # url = f"{base_url}{x}?page={page}"
        url = f"{x}?page={page}"

        # Send a GET request to the URL
        response = session.get(url)
        print(f"Fetching page: {url}")

        # Check if the request was successful
        if response.status_code == 200:
            
            # Parse the HTML content using BeautifulSoup
            soup = BeautifulSoup(response.content, "html.parser")
            
            # Loop through the product listings and extract the data
            cols = soup.find_all('div', class_='flex__row--start js_pagination_container')
            
            # for row in rows:
            #     cols = row.find_all('div', class_='flex__row--start js_pagination_container')
                
            for col in cols:
                products = col.find_all('div', class_='product__card')
    
                for product in products:
                    category = x
                    title = product.find('a', class_ = 'product__title').get_text()
                    price = product.find('div', class_='product__price--cur').text.strip()
        
                    product_categories.append(category)
                    product_titles.append(title)
                    product_prices.append(price)
    
        time.sleep(3)
        print("sleep 3 seconds")

Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=1
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=2
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=3
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=4
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=5
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=6
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=7
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=8
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=9
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=10
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=11
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=12
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=13
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=14
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=15
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=16
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=17
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=18
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=19
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=20
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=21
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=22
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=23
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=24
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=25
sleep 3 seconds
Fetching page: https://www.bakuelectronics.az/catalog/telefonlar-qadcetler/smartfonlar-mobil-telefonlar/?page=26
sleep 3 seconds

In [46]:
# Create a DataFrame from the lists and export

baku = pd.DataFrame({"Product Category": product_categories,
                     "Product Name": product_titles,
                     "Product Price": product_prices})

scraping_datetime = date.today()

baku.to_excel(f"results/baku.xlsx", index = False)

In [14]:
baku

,Product Category,Product Name,Product Price
0,https://www.bakuelectronics.az/catalog/telefon...,TELEFON XIAOMI 14 ULTRA 16GB/512GB BLACK,"2999,99"
1,https://www.bakuelectronics.az/catalog/telefon...,Smartfon Samsung Galaxy S24 Ultra 12GB/256GB T...,"2499,99"
2,https://www.bakuelectronics.az/catalog/telefon...,TELEFON MOTOROLA RAZR 40 ULTRA 8/256GB INFINIT...,"1799,99"
3,https://www.bakuelectronics.az/catalog/telefon...,Smartfon Apple iPhone 15 PRO MAX 256GB BLUE TI...,"3139,99"
4,https://www.bakuelectronics.az/catalog/telefon...,TELEFON XIAOMI 14 ULTRA 16GB/512GB WHITE,"2999,99"
...,...,...,...
515,https://www.bakuelectronics.az/catalog/telefon...,Smartfon Infinix GT 20 PRO 12GB/256GB 5G MECHA...,"899,99"
516,https://www.bakuelectronics.az/catalog/telefon...,Smartfon Infinix GT 20 PRO 12GB/256GB 5G MECHA...,"899,99"
517,https://www.bakuelectronics.az/catalog/telefon...,Smartfon Infinix GT 20 PRO 12GB/256GB 5G MECHA...,"899,99"
518,https://www.bakuelectronics.az/catalog/telefon...,Smartfon Redmi 13 6GB/128GB Ocean Blue NFC,"359,99"
519,https://www.bakuelectronics.az/catalog/telefon...,Smartfon Redmi 13 6GB/128GB Midnight Black NFC,"359,99"

## azerbaijan UMICO

In [11]:
# MPProductsList MPProductsList
import pandas as pd
import requests
import time
from bs4 import BeautifulSoup
from datetime import date
from tqdm import tqdm

!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (1.1.0)

In [12]:
#go to https://www.whatismybrowser.com/
nargiz = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
}
session = requests.Session()
# r = requests.get("https://www.bakuelectronics.az/catalog/", headers=headers)
# response = BeautifulSoup(r.text, features='html.parser')

url = "https://umico.az/categories"
response = requests.get(url, headers=nargiz)

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, "html.parser")

In [13]:
# Find the category listings
katalog = []
categories = soup.find("div", class_ = "MPCategories")
category = categories.find_all("a", href=True)

In [15]:
category

[<a class="MPCategory" href="/promo_page/69-evler-cehizle-dolsun-az"><span alt="Kateqoriya Evlər cehizlə dolsun!" class="MPCategory-Logo" title="Evlər cehizlə dolsun!"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Evlər cehizlə dolsun!</span></a>,
 <a class="MPCategory" href="/promo_page/68-mektebe-qayidish"><span alt="Kateqoriya Əla qiymətlər" class="MPCategory-Logo" title="Əla qiymətlər"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Əla qiymətlər</span></a>,
 <a class="MPCategory" href="/mega-discounts"><span alt="Kateqoriya &lt;span&gt;Mega&lt;/span&gt; endirimlər" class="MPCategory-Logo" title="&lt;span&gt;Mega&lt;/span&gt; endirimlər"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title"><span>Mega</span> endirimlər</span></a>,
 <a class="MPCategory" href="/categories/4497-dukan"><span alt="Kateqoriya Dükan bazarlıq" class="MPCategory-Logo" title="Dükan bazarlıq"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Dükan bazarlıq</span></a>,
 <a class="MPCategory" href="/categories/2-telefonlar-ve-aksessuarlar"><span alt="Kateqoriya Telefonlar, Smart cihazlar və telefon aksessuarları" class="MPCategory-Logo" title="Telefonlar, Smart cihazlar və telefon aksessuarları"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Telefonlar, Smart cihazlar və telefon aksessuarları</span></a>,
 <a class="MPCategory" href="/categories/15-noutbuklar-ve-komputer-texnikasi"><span alt="Kateqoriya Notbuk və kompüterlər" class="MPCategory-Logo" title="Notbuk və kompüterlər"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Notbuk və kompüterlər</span></a>,
 <a class="MPCategory" href="/categories/106-meishet-texnikasi"><span alt="Kateqoriya Məişət texnikası" class="MPCategory-Logo" title="Məişət texnikası"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Məişət texnikası</span></a>,
 <a class="MPCategory" href="/categories/70-tv-audio-ve-video"><span alt="Kateqoriya TV, audio və video" class="MPCategory-Logo" title="TV, audio və video"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">TV, audio və video</span></a>,
 <a class="MPCategory" href="/categories/937-ev-ve-bag-uchun-mehsullar"><span alt="Kateqoriya Ev əşyaları" class="MPCategory-Logo" title="Ev əşyaları"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Ev əşyaları</span></a>,
 <a class="MPCategory" href="/categories/257-gozellik-ve-saglamliq"><span alt="Kateqoriya Gözəllik və Sağlamlıq" class="MPCategory-Logo" title="Gözəllik və Sağlamlıq"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Gözəllik və Sağlamlıq</span></a>,
 <a class="MPCategory" href="/categories/2266-aksessuarlar-saatlar-bezek-eshyalari"><span alt="Kateqoriya Saat, zinət və bəzək əşyaları" class="MPCategory-Logo" title="Saat, zinət və bəzək əşyaları"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Saat, zinət və bəzək əşyaları</span></a>,
 <a class="MPCategory" href="/categories/4835-oyunchular-uchun-mehsullar"><span alt="Kateqoriya Umico Gaming" class="MPCategory-Logo" title="Umico Gaming"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Umico Gaming</span></a>,
 <a class="MPCategory" href="/categories/2627-temir-ve-tikinti"><span alt="Kateqoriya Təmir-tikinti" class="MPCategory-Logo" title="Təmir-tikinti"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Təmir-tikinti</span></a>,
 <a class="MPCategory" href="/categories/779-analar-ve-balalar-uchun"><span alt="Kateqoriya Uşaqlar üçün məhsullar" class="MPCategory-Logo" title="Uşaqlar üçün məhsullar"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Uşaqlar üçün məhsullar</span></a>,
 <a class="MPCategory" href="/categories/1657-ofis-ve-mekteb-levazimatlari"><span alt="Kateqoriya Ofis və məktəb ləvazimatları, kitabla" class="MPCategory-Logo" title="Ofis və məktəb ləvazimatları, kitabla"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Ofis və məktəb ləvazimatları, kitabla</span></a>,
 <a class="MPCategory" href="/categories/2164-ev-heyvanlari-uchun-mehsullar"><span alt="Kateqoriya Ev heyvanları üçün məhsullar" class="MPCategory-Logo" title="Ev heyvanları üçün məhsullar"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Ev heyvanları üçün məhsullar</span></a>,
 <a class="MPCategory" href="/categories/3003-geyim-ve-ayaqqabi"><span alt="Kateqoriya Geyim,ayaqqabı və aksessuarlar" class="MPCategory-Logo" title="Geyim,ayaqqabı və aksessuarlar"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Geyim,ayaqqabı və aksessuarlar</span></a>,
 <a class="MPCategory" href="/categories/516-idman-ve-feal-istirahet"><span alt="Kateqoriya Idman və Əyləncə" class="MPCategory-Logo" title="Idman və Əyləncə"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Idman və Əyləncə</span></a>,
 <a class="MPCategory" href="/categories/1708-avtomobil-uchun-mehsullar"><span alt="Kateqoriya Avtomobil məhsulları" class="MPCategory-Logo" title="Avtomobil məhsulları"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Avtomobil məhsulları</span></a>,
 <a class="MPCategory" href="/categories/1232-bag-ve-bostan"><span alt="Kateqoriya Bağ üçün məhsullar" class="MPCategory-Logo" title="Bağ üçün məhsullar"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Bağ üçün məhsullar</span></a>,
 <a class="MPCategory" href="/categories/3890-outlet"><span alt="Kateqoriya Outlet" class="MPCategory-Logo" title="Outlet"><span class="MPCategory-Loader"><span class="Icon"></span></span></span> <span class="MPCategory-Title">Outlet</span></a>]

In [16]:
urlsuperbase = "https://umico.az" 
for cat in category:
    link = urlsuperbase+cat["href"]
    katalog.append(link)

category_list = katalog[3:20] #choose only the categories from dukan to garden
category_list

['https://umico.az/categories/4497-dukan',
 'https://umico.az/categories/2-telefonlar-ve-aksessuarlar',
 'https://umico.az/categories/15-noutbuklar-ve-komputer-texnikasi',
 'https://umico.az/categories/106-meishet-texnikasi',
 'https://umico.az/categories/70-tv-audio-ve-video',
 'https://umico.az/categories/937-ev-ve-bag-uchun-mehsullar',
 'https://umico.az/categories/257-gozellik-ve-saglamliq',
 'https://umico.az/categories/2266-aksessuarlar-saatlar-bezek-eshyalari',
 'https://umico.az/categories/4835-oyunchular-uchun-mehsullar',
 'https://umico.az/categories/2627-temir-ve-tikinti',
 'https://umico.az/categories/779-analar-ve-balalar-uchun',
 'https://umico.az/categories/1657-ofis-ve-mekteb-levazimatlari',
 'https://umico.az/categories/2164-ev-heyvanlari-uchun-mehsullar',
 'https://umico.az/categories/3003-geyim-ve-ayaqqabi',
 'https://umico.az/categories/516-idman-ve-feal-istirahet',
 'https://umico.az/categories/1708-avtomobil-uchun-mehsullar',
 'https://umico.az/categories/1232-bag-ve-bostan']

In [17]:
#scraping
n = 1 #how many pages
product_categories = []
product_descs = []
product_prices = []
product_prices_after_discount = [] #if any
product_seller_name = []

for cat in category_list:
    for page in range(1, n+1, 1):
        # url = f"{base_url}{x}?page={page}"
        umico_url = f"{cat}?page={page}"

        # Send a GET request to the URL
        response = session.get(umico_url)
        print(f"Fetching page: {umico_url}")
        
        # Check if the request was successful
        if response.status_code == 200:
            soup_umico = BeautifulSoup(response.content, "html.parser")
            items = soup_umico.find_all("div",{"class": "MPProductItem"})

            for item in items:
                category = cat.rsplit("/", 3)[3]
                # category = cat
                try:
                    price_after_discount = item.find("span",{"data-info": "item-desc-price-new"}).text.strip()
                except Exception as e: 
                    price_after_discount = None
                # print(price_after_discount) #to show the prices

                try:
                    price = item.find("span",{"data-info": "item-desc-price-old"}).text.strip()
                except Exception as e: 
                    price = None

                try:
                    desc = item.find("span",{"class": "MPTitle"}).text.strip()
                except Exception as e: 
                    desc = None
                try:
                    seller = item.find("div",{"class": "line-clamp-2 text-[#1e244d] text-[11px]"}).text.strip()
                except Exception as e: 
                    seller = None

                product_categories.append(category)
                product_descs.append(desc)
                product_prices.append(price)
                product_prices_after_discount.append(price_after_discount)
                product_seller_name.append(seller)
        time.sleep(1) #seconds
print('done')

umico = pd.DataFrame({"Category": product_categories,
                     "Name": product_descs,
                     "Price": product_prices,
                     "Price After Discount": product_prices_after_discount,
                     "Seller": product_seller_name})

Fetching page: https://umico.az/categories/4497-dukan?page=1
Fetching page: https://umico.az/categories/2-telefonlar-ve-aksessuarlar?page=1
Fetching page: https://umico.az/categories/15-noutbuklar-ve-komputer-texnikasi?page=1
Fetching page: https://umico.az/categories/106-meishet-texnikasi?page=1
Fetching page: https://umico.az/categories/70-tv-audio-ve-video?page=1
Fetching page: https://umico.az/categories/937-ev-ve-bag-uchun-mehsullar?page=1
Fetching page: https://umico.az/categories/257-gozellik-ve-saglamliq?page=1
Fetching page: https://umico.az/categories/2266-aksessuarlar-saatlar-bezek-eshyalari?page=1
Fetching page: https://umico.az/categories/4835-oyunchular-uchun-mehsullar?page=1
Fetching page: https://umico.az/categories/2627-temir-ve-tikinti?page=1
Fetching page: https://umico.az/categories/779-analar-ve-balalar-uchun?page=1
Fetching page: https://umico.az/categories/1657-ofis-ve-mekteb-levazimatlari?page=1
Fetching page: https://umico.az/categories/2164-ev-heyvanlari-uchun-mehsullar?page=1
Fetching page: https://umico.az/categories/3003-geyim-ve-ayaqqabi?page=1
Fetching page: https://umico.az/categories/516-idman-ve-feal-istirahet?page=1
Fetching page: https://umico.az/categories/1708-avtomobil-uchun-mehsullar?page=1
Fetching page: https://umico.az/categories/1232-bag-ve-bostan?page=1
done

In [ ]:
#pandas

In [18]:
umico

,Category,Name,Price,Price After Discount,Seller
0,4497-dukan,Xiyar Melit 500(+-50) q,0.30 ₼,0.22 ₼,Satıcı: Dükan
1,4497-dukan,Banan 1000(+-50) q,2.89 ₼,None,Satıcı: Dükan
2,4497-dukan,"Yumurta Hacıqabul, iri, ağ, 1 əd",0.11 ₼,None,Satıcı: Dükan
3,4497-dukan,Süd Milla 3.2% 1 l,2.59 ₼,None,Satıcı: Dükan
4,4497-dukan,Kağız salfetlər Sun Maxi by Dükan,0.99 ₼,0.79 ₼,Satıcı: Dükan
...,...,...,...,...,...
466,1232-bag-ve-bostan,Su nasosu Makute MKFC-12,34.00 ₼,None,Satıcı: Umico Market
467,1232-bag-ve-bostan,"Bağ masası 6159/A, 150x90x75 sm, qəhvəyi",280.59 ₼,224.47 ₼,Satıcı: Umico Market
468,1232-bag-ve-bostan,Benzinli trimmer Ryobi RBC31SBO,705.33 ₼,None,Satıcı: Pro Tool
469,1232-bag-ve-bostan,"Bağ üçün mebel dəsti Okyanus SP_6312, 4 əşya, ...",1 705.88 ₼,1 535.29 ₼,Satıcı: Umico Market
470,1232-bag-ve-bostan,Akkumulyator çiləmə cihazı P.I.T. PSY20H-15A SOLO,279.38 ₼,None,Satıcı: Umico Market

In [19]:
umico.tail()

,Category,Name,Price,Price After Discount,Seller
466,1232-bag-ve-bostan,Su nasosu Makute MKFC-12,34.00 ₼,None,Satıcı: Umico Market
467,1232-bag-ve-bostan,"Bağ masası 6159/A, 150x90x75 sm, qəhvəyi",280.59 ₼,224.47 ₼,Satıcı: Umico Market
468,1232-bag-ve-bostan,Benzinli trimmer Ryobi RBC31SBO,705.33 ₼,None,Satıcı: Pro Tool
469,1232-bag-ve-bostan,"Bağ üçün mebel dəsti Okyanus SP_6312, 4 əşya, ...",1 705.88 ₼,1 535.29 ₼,Satıcı: Umico Market
470,1232-bag-ve-bostan,Akkumulyator çiləmə cihazı P.I.T. PSY20H-15A SOLO,279.38 ₼,None,Satıcı: Umico Market

In [20]:
umico.head(3)

,Category,Name,Price,Price After Discount,Seller
0,4497-dukan,Xiyar Melit 500(+-50) q,0.30 ₼,0.22 ₼,Satıcı: Dükan
1,4497-dukan,Banan 1000(+-50) q,2.89 ₼,None,Satıcı: Dükan
2,4497-dukan,"Yumurta Hacıqabul, iri, ağ, 1 əd",0.11 ₼,None,Satıcı: Dükan

In [21]:
umico.to_excel(f"D:/Nari/ESCAP2024_codding/Bangkok/umico_19sept.xlsx", index = False)